'use strict';
function buildText(p){const entries=Object.entries(p.powers);return entries.length?entries.slice(-3).map(([id,v])=>{const d=powerDef(id);return(d?d.name:id)+(v>1?' ×'+v:'')}).join(' · '):'sin mejoras'}
function scoreData(s){const m=modeOf(s);if(m.id==='teams')return[{label:'EQUIPO AZUL',score:s.teamScore[0],color:TEAM_COLORS[0]},{label:'EQUIPO ROSA',score:s.teamScore[1],color:TEAM_COLORS[1]}];return s.players.map(p=>({label:(p.i===me?'TÚ':'P'+(p.i+1)),score:p.score,color:PLAYER_COLORS[p.i]}))}
function syncUI(s){if(!s)return;const m=modeOf(s);$('modeName').textContent=m.name;$('roundNum').textContent=s.round;
  const sb=$('scoreboard');sb.innerHTML='';for(const item of scoreData(s)){const el=document.createElement('div');el.className='score-pill';el.style.borderColor=item.color+'66';el.innerHTML='<span style="color:'+item.color+'">'+item.label+'</span><b>'+item.score+'</b>';sb.appendChild(el)}
  const msg=$('centerMessage');if(s.phase==='count'){msg.textContent=Math.ceil(s.count);msg.classList.remove('hidden')}else if(s.phase==='round'){msg.textContent='RONDA TERMINADA';msg.classList.remove('hidden')}else msg.classList.add('hidden');
  readyUI(s);draftUI(s);endUI(s)
}
function readyUI(s){const o=$('readyOverlay');if(s.phase!=='ready'){o.classList.add('hidden');return}o.classList.remove('hidden');const m=modeOf(s),connected=s.connected.filter(Boolean).length,full=connected===m.players,mineReady=me!=null&&!!s.ready[me],readyCount=s.ready.filter(Boolean).length;$('readyTitle').textContent=!full?'FALTA GENTE':(mineReady?'LISTO.':'¿PREPARADO?');$('readySubtitle').textContent=!full?'Comparte el enlace. La sala necesita '+m.players+' jugadores.':(mineReady?'Esperando a que el resto confirme.':'Cuando todos pulsen listo empieza la partida.');$('readyBtn').disabled=!full||mineReady||me==null;$('readyBtn').textContent=!full?'ESPERANDO JUGADORES':(mineReady?'LISTO ✓':'ESTOY LISTO');$('readyState').textContent=connected+' / '+m.players+' conectados · '+readyCount+' / '+m.players+' listos'}
function draftUI(s){const o=$('upgradeOverlay');if(s.phase!=='pick'||me==null){o.classList.add('hidden');o.dataset.sig='';pickLock=false;return}o.classList.remove('hidden');const opts=s.opts[me]||[],chosen=s.picked[me],p=s.players[me],sig=opts.join('|')+'|'+chosen+'|'+p.lossStreak;if(o.dataset.sig===sig)return;o.dataset.sig=sig;$('upgradeCards').innerHTML='';opts.forEach((id,n)=>{const d=powerDef(id);if(!d)return;const bt=document.createElement('button');bt.className='power-card rarity-'+d.rarity;bt.disabled=chosen!=null;bt.innerHTML='<span class="rarity">'+RARITY_LABEL[d.rarity]+'</span><h3>'+d.name+'</h3><p>'+d.desc+'</p><span class="lvl">NIVEL '+(p.powers[id]||0)+' / '+(d.max||1)+'</span>';bt.onclick=()=>{if(pickLock)return;pickLock=true;if(host)chooseUpgrade(0,n);else conn?.send({type:'pick',n})};$('upgradeCards').appendChild(bt)});const luck=p.lossStreak?(' · Comeback luck +'+p.lossStreak):'';$('upgradeKicker').textContent='ELIGE TU MEJORA'+luck;$('pickStatus').textContent=chosen==null?'Las mejoras generales desarrollan la build. Legendarias e ilegales modifican las habilidades de MIX.':'Elegido. Esperando al resto…'}
function resultForMe(s){if(!s.matchWinner||me==null)return false;if(s.matchWinner.type==='player')return s.matchWinner.seat===me;return s.players[me].team===s.matchWinner.team}
function accuracy(p){return p.stats.shots?Math.round(p.stats.hits/p.stats.shots*100):0}
function endUI(s){const o=$('matchOverlay');if(s.phase!=='end'||me==null){o.classList.add('hidden');return}o.classList.remove('hidden');const win=resultForMe(s),p=s.players[me];$('matchTitle').textContent=win?'VICTORIA':'DERROTA';$('matchSubtitle').textContent=win?'La torreta ha salido viva de este crimen.':'La build rival te ha pasado por encima.';$('statDamage').textContent=Math.round(p.stats.damage);$('statAccuracy').textContent=accuracy(p)+'%';$('statKills').textContent=p.stats.kills;$('statPickups').textContent=p.stats.pickups;const ready=!!s.rematch[me],count=s.rematch.filter(Boolean).length,m=modeOf(s);$('rematchBtn').disabled=ready;$('rematchBtn').textContent=ready?'REVANCHA LISTA ✓':'LISTO PARA REVANCHA';$('rematchStatus').textContent=ready?(count===m.players?'Reiniciando…':'Esperando al resto…'):(count?count+' / '+m.players+' ya están listos.':'La revancha empieza cuando todos acepten.')}

function drawGrid(){ctx.strokeStyle='#151b2a';ctx.lineWidth=1;for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function drawArenaScore(s){}
function drawBarrels(p,i){const shown=Math.min(7,p.s.n),perp=p.a+Math.PI/2;for(let k=0;k<shown;k++){const off=(k-(shown-1)/2)*6.5,ox=Math.cos(perp)*off,oy=Math.sin(perp)*off;ctx.strokeStyle=PLAYER_COLORS[i];ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x+ox,p.y+oy);ctx.lineTo(p.x+ox+Math.cos(p.a)*39,p.y+oy+Math.sin(p.a)*39);ctx.stroke()}}
function drawHpAbove(p){const w=96,h=11,x=p.x-w/2,y=p.y-49,ratio=Math.max(0,p.hp/p.max);ctx.fillStyle='#05070bdd';ctx.fillRect(x-2,y-2,w+4,h+4);ctx.fillStyle=ratio>.45?PLAYER_COLORS[p.i]:(ratio>.2?'#ffd166':'#ff596f');ctx.fillRect(x,y,w*ratio,h);ctx.strokeStyle='#ffffff40';ctx.lineWidth=1.5;ctx.strokeRect(x,y,w,h);ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillStyle='#f7f9ff';ctx.fillText(Math.max(0,Math.ceil(p.hp))+' / '+p.max,p.x,y-6);if(p.i===me){ctx.font='900 10px system-ui';ctx.fillStyle=p.specialCd<=0?'#ffd166':'#7f899e';ctx.fillText(p.specialCd<=0?'E · BOLA DE CAÑÓN LISTA':'E · '+p.specialCd.toFixed(1)+' s',p.x,y+h+16)}}
function drawTurret(p,n){const color=PLAYER_COLORS[p.i];ctx.save();if(p.inv&&Math.floor(n/70)%2===0)ctx.globalAlpha=.38;ctx.shadowColor=color;ctx.shadowBlur=18;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#0a0d15';ctx.beginPath();ctx.arc(p.x,p.y,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.stroke();drawBarrels(p,p.i);if(p.shield){ctx.strokeStyle='#f8fbff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,31,0,Math.PI*2);ctx.stroke()}if(p.fx.burn>0){ctx.strokeStyle='#ff7a52';ctx.beginPath();ctx.arc(p.x,p.y,35,0,Math.PI*2);ctx.stroke()}if(p.fx.slow>0){ctx.strokeStyle='#75bfff';ctx.beginPath();ctx.arc(p.x,p.y,38,0,Math.PI*2);ctx.stroke()}ctx.restore();drawHpAbove(p)}
const seenEffects=new Set();
function drawEffects(s){if(!s?.effects)return;for(const e of s.effects){if(!seenEffects.has(e.id)){seenEffects.add(e.id);if(['barrel','cannon'].includes(e.type))shake=Math.max(shake,e.type==='cannon'?24:18)}const t=1-e.life/e.duration,alpha=Math.max(0,e.life/e.duration);ctx.save();ctx.globalCompositeOperation='lighter';const grad=ctx.createRadialGradient(e.x,e.y,0,e.x,e.y,e.radius);grad.addColorStop(0,e.color+'dd');grad.addColorStop(.22,e.color+'88');grad.addColorStop(1,e.color+'00');ctx.globalAlpha=.75*alpha;ctx.fillStyle=grad;ctx.beginPath();ctx.arc(e.x,e.y,e.radius*(.45+.55*t),0,Math.PI*2);ctx.fill();ctx.globalAlpha=alpha;ctx.strokeStyle=e.color;ctx.lineWidth=Math.max(2,8*(1-t));ctx.beginPath();ctx.arc(e.x,e.y,e.radius*(.18+.82*t),0,Math.PI*2);ctx.stroke();const seed=(e.id||'x').split('').reduce((a,ch)=>a+ch.charCodeAt(0),0);const count=e.type==='cannon'?18:e.type==='barrel'?14:8;for(let k=0;k<count;k++){const a=(Math.PI*2/count)*k+seed*.013,dist=e.radius*t*(.45+((k*37)%100)/180);ctx.globalAlpha=alpha*.9;ctx.fillStyle=k%2?e.color:'#fff2cc';ctx.beginPath();ctx.arc(e.x+Math.cos(a)*dist,e.y+Math.sin(a)*dist,2+(k%3),0,Math.PI*2);ctx.fill()}ctx.restore()}}
function drawStorm(s){const st=s?.storm;if(!st)return;const remain=st.start-st.elapsed;if(st.active){ctx.save();ctx.fillStyle='rgba(91,38,130,.23)';ctx.beginPath();ctx.rect(0,0,W,H);ctx.arc(W/2,H/2,Math.max(0,st.radius),0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#bd67ff';ctx.shadowColor='#bd67ff';ctx.shadowBlur=16;ctx.lineWidth=4;ctx.beginPath();ctx.arc(W/2,H/2,st.radius,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.save();ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.fillStyle='#d59aff';ctx.fillText('TORMENTA',W/2,54);ctx.restore()}else if(remain<=8&&remain>0){ctx.save();ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.fillStyle='#c79be6';ctx.fillText('TORMENTA EN '+Math.ceil(remain)+' s',W/2,54);ctx.restore()}}
function drawBarrel(b){if(!b.alive)return;ctx.save();ctx.shadowColor='#ff643f';ctx.shadowBlur=12;ctx.fillStyle='#8d2f24';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ff9b61';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#1a0d0b';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('!',b.x,b.y+1);ctx.restore()}
function draw(s,n){ctx.clearRect(0,0,W,H);const map=MAPS[s?.map||0],grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,map.bg);grad.addColorStop(1,'#07090f');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);drawGrid();ctx.strokeStyle='#303a52';ctx.lineWidth=2;ctx.strokeRect(48,48,W-96,H-96);for(const o of map.obs){ctx.fillStyle='#121827';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#303a52';ctx.strokeRect(o.x,o.y,o.w,o.h)}if(!s)return;drawStorm(s);s.barrels.forEach(drawBarrel);s.pickups.forEach(it=>{const d=PICKUPS[it.type];ctx.save();ctx.shadowColor=d.color;ctx.shadowBlur=18;ctx.strokeStyle=d.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(it.x,it.y,16,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.18;ctx.fillStyle=d.color;ctx.fill();ctx.restore()});s.bullets.forEach(b=>{const bc=b.special?'#ffd19a':b.fire?'#ff7a52':b.frost?'#75bfff':b.shock?'#ffe26f':PLAYER_COLORS[b.owner];ctx.save();ctx.shadowColor=bc;ctx.shadowBlur=b.special?28:12;if(b.special){const g=ctx.createRadialGradient(b.x-5,b.y-5,2,b.x,b.y,b.r);g.addColorStop(0,'#fff8dc');g.addColorStop(.35,'#ffc15c');g.addColorStop(1,'#7c351c');ctx.fillStyle=g}else ctx.fillStyle=bc;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();if(b.special){ctx.strokeStyle='#fff0c2';ctx.lineWidth=3;ctx.stroke()}ctx.restore()});drawEffects(s);s.players.forEach(p=>{if(p.alive)drawTurret(p,n)})}
function frame(n){const dt=Math.min(.05,(n-lastFrame)/1000);lastFrame=n;if(!host&&conn?.open&&me!=null){sendAccumulator+=dt;if(sendAccumulator>.033){sendAccumulator=0;conn.send({type:'input',k:mine})}}const s=host?game:view;if(shake){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.8;draw(s,n);ctx.restore()}else draw(s,n);syncUI(s);requestAnimationFrame(frame)}

function pointerPos(e){const r=cv.getBoundingClientRect();mine.ax=(e.clientX-r.left)*W/r.width;mine.ay=(e.clientY-r.top)*H/r.height}
addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;if(['KeyW','KeyA','KeyS','KeyD','Space','KeyE'].includes(e.code))e.preventDefault();if(e.code==='KeyW')mine.u=1;if(e.code==='KeyS')mine.d=1;if(e.code==='KeyA')mine.l=1;if(e.code==='KeyD')mine.r=1;if(e.code==='Space')mine.dash=1;if(e.code==='KeyE')mine.special=1},{passive:false});
addEventListener('keyup',e=>{if(e.code==='KeyW')mine.u=0;if(e.code==='KeyS')mine.d=0;if(e.code==='KeyA')mine.l=0;if(e.code==='KeyD')mine.r=0;if(e.code==='Space')mine.dash=0;if(e.code==='KeyE')mine.special=0});
cv.onpointermove=pointerPos;cv.onpointerdown=e=>{pointerPos(e);if(e.button===0)mine.fire=1};addEventListener('pointerup',()=>mine.fire=0);addEventListener('blur',()=>{mine.u=mine.d=mine.l=mine.r=mine.fire=mine.dash=mine.special=0});

for(const b of document.querySelectorAll('.mode-card'))b.addEventListener('click',()=>{selectedMode=b.dataset.mode;document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x===b))});
$('hostBtn').onclick=hostGame;
$('joinForm').onsubmit=e=>{e.preventDefault();joinGame($('roomInput').value)};
$('roomInput').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
$('leaveBtn').onclick=()=>{const u=new URL(location.href);u.searchParams.delete('room');history.replaceState({},'',u);clean()};
$('copyBtn').onclick=async()=>{const u=new URL(location.href);u.searchParams.set('room',code);try{await navigator.clipboard.writeText(u.toString());$('copyBtn').textContent='COPIADO';setTimeout(()=>$('copyBtn').textContent='COPIAR ENLACE',1200)}catch{prompt('Copia el enlace:',u.toString())}};
$('readyBtn').onclick=()=>{if(me==null)return;if(host)setReady(0,'ready');else conn?.send({type:'ready'})};
$('rematchBtn').onclick=()=>{if(me==null)return;if(host)setReady(0,'rematch');else conn?.send({type:'rematch'})};
$('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('canvasFrame').requestFullscreen()}catch(e){console.warn(e)}};
document.addEventListener('fullscreenchange',()=>{$('fullscreenBtn').textContent=document.fullscreenElement?'SALIR DE PANTALLA COMPLETA':'PANTALLA COMPLETA'});

const invite=new URL(location.href).searchParams.get('room');if(invite)$('roomInput').value=invite.toUpperCase().slice(0,6);
if(typeof Peer==='undefined')status('No se pudo cargar la conexión online. Recarga.',true);else if(invite)setTimeout(()=>joinGame(invite),0);
requestAnimationFrame(frame);