(()=>{
'use strict';
const $=id=>document.getElementById(id),cv=$('game'),c=cv.getContext('2d'),W=960,H=540,PFX='fight-random-',COL=['#47e8ff','#ff4fa3'];
const OBS=[{x:452,y:150,w:56,h:90},{x:452,y:300,w:56,h:90}];
const POW={
 multi:['Más plomo','+1 proyectil.','common'],rapid:['Gatillo nervioso','+24% cadencia.','common'],speed:['Cafeína','+15% velocidad.','common'],tank:['Carne extra','+25 vida máxima.','common'],
 heavy:['Bala gorda','+7 daño y empuje.','rare'],bounce:['Rebote','Las balas rebotan +1 vez.','rare'],dash:['Dash adicto','Dash más fuerte y frecuente.','rare'],shield:['Escudo gratis','Bloqueas +1 impacto por ronda.','rare'],
 homing:['Aim assist ilegal','Las balas corrigen trayectoria.','epic'],boom:['Problema explosivo','Impactos con daño extra.','epic'],glass:['Cañón de cristal','+45% daño, -15% vida.','legendary'],hell:['ERROR 404: equilibrio','+2 balas, -15% daño.','illegal']
};
const R={common:'COMÚN',rare:'RARO',epic:'ÉPICO',legendary:'LEGENDARIO',illegal:'ILEGAL'};
let peer,conn,host=false,me=0,code='',g=null,view=null,timer=null,last=performance.now(),acc=0,pickLock=false,shake=0;
const mine={u:0,d:0,l:0,r:0,fire:0,dash:0,ax:480,ay:270},other={u:0,d:0,l:0,r:0,fire:0,dash:0,ax:480,ay:270};
function stats(){return{spd:220,rate:.4,dmg:16,bs:540,size:5,n:1,bounce:0,homing:0,boom:0,dash:540,dc:1.65,shield:0,knock:90}}
function player(i){return{i,x:i?790:170,y:270,vx:0,vy:0,r:18,hp:100,max:100,score:0,a:i?Math.PI:0,shot:0,dc:0,dt:0,inv:0,pd:0,shield:0,s:stats(),p:{}}}
function fresh(){return{phase:'wait',round:1,count:0,t:0,winner:null,p:[player(0),player(1)],b:[],opts:[[],[]],picked:[null,null]}}
function startRound(){g.phase='count';g.count=2.2;g.b=[];g.picked=[null,null];g.opts=[[],[]];g.p.forEach((p,i)=>{p.x=i?790:170;p.y=270;p.vx=p.vy=0;p.hp=p.max;p.shot=p.dc=p.dt=p.inv=0;p.pd=0;p.shield=p.s.shield})}
function options(i){let pool=Object.keys(POW).filter(x=>x!=='hell'||g.round>=5),out=[];while(out.length<3){let x=pool[Math.floor(Math.random()*pool.length)];if(!out.includes(x))out.push(x)}return out}
function upgrade(i,id){let p=g.p[i];p.p[id]=(p.p[id]||0)+1;switch(id){case'multi':p.s.n++;break;case'rapid':p.s.rate*=.76;break;case'speed':p.s.spd*=1.15;break;case'tank':p.max+=25;break;case'heavy':p.s.dmg+=7;p.s.size+=1.2;p.s.knock+=30;break;case'bounce':p.s.bounce++;break;case'dash':p.s.dc*=.8;p.s.dash*=1.12;break;case'shield':p.s.shield++;break;case'homing':p.s.homing+=.8;break;case'boom':p.s.boom+=.24;break;case'glass':p.s.dmg*=1.45;p.max=Math.max(45,Math.round(p.max*.85));break;case'hell':p.s.n+=2;p.s.dmg*=.85;break}}
function choose(i,n){if(!host||g.phase!=='pick'||g.picked[i]!=null)return;let id=g.opts[i][n];if(!id)return;g.picked[i]=n;upgrade(i,id);if(g.picked.every(x=>x!=null))g.t=.7;send(true)}
function roundEnd(loser){if(g.phase!=='play')return;let w=1-loser;g.p[w].score++;if(g.p[w].score>=5){g.phase='end';g.winner=w}else{g.phase='round';g.t=1.2}send(true)}
function sim(dt){if(!g)return;if(g.phase==='count'){g.count-=dt;if(g.count<=0)g.phase='play';return}if(g.phase==='round'){g.t-=dt;if(g.t<=0){g.round++;g.phase='pick';g.opts=[options(0),options(1)];g.picked=[null,null];pickLock=false;send(true)}return}if(g.phase==='pick'){if(g.picked.every(x=>x!=null)){g.t-=dt;if(g.t<=0)startRound()}return}if(g.phase!=='play')return;[mine,other].forEach((inp,i)=>move(g.p[i],inp,dt));bullets(dt)}
function move(p,k,dt){p.shot=Math.max(0,p.shot-dt);p.dc=Math.max(0,p.dc-dt);p.dt=Math.max(0,p.dt-dt);p.inv=Math.max(0,p.inv-dt);let ax=k.ax-p.x,ay=k.ay-p.y;if(Math.abs(ax)+Math.abs(ay)>1)p.a=Math.atan2(ay,ax);let x=k.r-k.l,y=k.d-k.u,m=Math.hypot(x,y)||1;x/=m;y/=m;if(k.dash&&!p.pd&&p.dc<=0){if(!x&&!y){x=Math.cos(p.a);y=Math.sin(p.a)}p.vx=x*p.s.dash;p.vy=y*p.s.dash;p.dt=.15;p.inv=.12;p.dc=p.s.dc}p.pd=k.dash;if(p.dt<=0){let q=1-Math.exp(-13*dt);p.vx+=(x*p.s.spd-p.vx)*q;p.vy+=(y*p.s.spd-p.vy)*q}else{p.vx*=.88;p.vy*=.88}p.x+=p.vx*dt;p.y+=p.vy*dt;collide(p);if(k.fire&&p.shot<=0){fire(p);p.shot=Math.max(.07,p.s.rate)}}
function collide(p){p.x=Math.max(53,Math.min(907,p.x));p.y=Math.max(53,Math.min(487,p.y));for(const o of OBS){let nx=Math.max(o.x,Math.min(p.x,o.x+o.w)),ny=Math.max(o.y,Math.min(p.y,o.y+o.h)),dx=p.x-nx,dy=p.y-ny,d=Math.hypot(dx,dy);if(d<p.r){if(d<.1){dx=p.x<480?-1:1;dy=0;d=1}p.x+=dx/d*(p.r-d);p.y+=dy/d*(p.r-d)}}}
function fire(p){let n=p.s.n,spread=.13*(n-1);for(let i=0;i<n;i++){let a=p.a+(n===1?0:(i/(n-1)-.5)*spread);g.b.push({x:p.x+Math.cos(a)*27,y:p.y+Math.sin(a)*27,vx:Math.cos(a)*p.s.bs,vy:Math.sin(a)*p.s.bs,r:p.s.size,o:p.i,d:p.s.dmg,bo:p.s.bounce,h:p.s.homing,e:p.s.boom,life:1.8})}}
function bullets(dt){for(let i=g.b.length-1;i>=0;i--){let b=g.b[i],t=g.p[1-b.o];b.life-=dt;if(b.life<=0){g.b.splice(i,1);continue}if(b.h){let a=Math.atan2(t.y-b.y,t.x-b.x),q=Math.atan2(b.vy,b.vx),df=((a-q+Math.PI*3)%(Math.PI*2))-Math.PI,s=Math.hypot(b.vx,b.vy);q+=Math.max(-b.h*dt,Math.min(b.h*dt,df));b.vx=Math.cos(q)*s;b.vy=Math.sin(q)*s}b.x+=b.vx*dt;b.y+=b.vy*dt;if(wall(b)||obstacle(b)){if(b.dead){g.b.splice(i,1);continue}}if(Math.hypot(b.x-t.x,b.y-t.y)<b.r+t.r){g.b.splice(i,1);hit(t,b)}}}
function bounce(b,axis){if(b.bo>0){b.bo--;b[axis]*=-1}else b.dead=1}
function wall(b){let h=0;if(b.x<40||b.x>920){b.x=Math.max(40,Math.min(920,b.x));bounce(b,'vx');h=1}if(!b.dead&&(b.y<40||b.y>500)){b.y=Math.max(40,Math.min(500,b.y));bounce(b,'vy');h=1}return h}
function obstacle(b){for(const o of OBS)if(b.x>o.x-b.r&&b.x<o.x+o.w+b.r&&b.y>o.y-b.r&&b.y<o.y+o.h+b.r){let dx=Math.min(Math.abs(b.x-o.x),Math.abs(b.x-o.x-o.w)),dy=Math.min(Math.abs(b.y-o.y),Math.abs(b.y-o.y-o.h));bounce(b,dx<dy?'vx':'vy');return 1}return 0}
function hit(t,b){if(t.inv>0)return;if(t.shield>0){t.shield--;t.inv=.15;return}let a=g.p[b.o],d=b.d*(1+b.e);t.hp-=d;t.vx+=b.vx/Math.hypot(b.vx,b.vy)*a.s.knock;t.vy+=b.vy/Math.hypot(b.vx,b.vy)*a.s.knock;shake=7;if(t.hp<=0)roundEnd(t.i)}
function send(force){if(host&&conn?.open&&(force||acc>.05)){acc=0;conn.send({type:'s',g:JSON.parse(JSON.stringify(g))})}}
function hostLoop(){clearInterval(timer);let p=performance.now();timer=setInterval(()=>{let n=performance.now(),dt=Math.min(.035,(n-p)/1000);p=n;sim(dt);acc+=dt;send(0);view=g},1000/60)}
function net(txt,on){$('netText').textContent=txt;$('netPill').classList.toggle('online',!!on)}
function status(t,e){$('lobbyStatus').textContent=t;$('lobbyStatus').classList.toggle('error',!!e)}
function room(){let x='',s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let i=0;i<6;i++)x+=s[Math.floor(Math.random()*s.length)];return x}
function clean(){clearInterval(timer);try{conn?.close()}catch{}try{peer?.destroy()}catch{}peer=conn=null;host=0;g=view=null;$('lobby').classList.remove('hidden');$('roomPanel').classList.add('hidden');$('gameWrap').classList.add('hidden');net('offline');}
function common(){peer.on('error',e=>{console.error(e);status(e.type==='peer-unavailable'?'No existe esa sala.':'Error de conexión. Prueba otra vez.',1);net('error')})}
function show(){ $('lobby').classList.add('hidden');$('roomPanel').classList.remove('hidden');$('gameWrap').classList.remove('hidden');$('roomCode').textContent=code;let u=new URL(location.href);u.searchParams.set('room',code);history.replaceState({},'',u)}
function hostGame(){clean();host=1;me=0;code=room();net('conectando…');peer=new Peer(PFX+code,{debug:1});common();peer.on('open',()=>{show();g=fresh();view=g;net('esperando rival')});peer.on('connection',x=>{if(conn?.open){x.close();return}conn=x;bind()})}
function joinGame(x){x=(x||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(x.length!==6){status('El código tiene 6 caracteres.',1);return}clean();host=0;me=1;code=x;net('conectando…');peer=new Peer({debug:1});common();peer.on('open',()=>{conn=peer.connect(PFX+code,{reliable:true});bind()})}
function bind(){conn.on('open',()=>{show();net('online',1);if(host){g=fresh();startRound();hostLoop();conn.send({type:'welcome',g:JSON.parse(JSON.stringify(g))})}});conn.on('data',d=>{if(host){if(d.type==='i')Object.assign(other,d.k);if(d.type==='pick')choose(1,+d.n);if(d.type==='rematch'&&g.phase==='end'){g=fresh();startRound();send(1)}}else if(d.type==='s'||d.type==='welcome')view=d.g});conn.on('close',()=>net('rival desconectado'))}
function sync(s){if(!s)return;let a=s.p[0],b=s.p[1];$('p1Score').textContent=a.score;$('p2Score').textContent=b.score;$('roundNum').textContent=s.round;$('p1Hp').style.width=Math.max(0,a.hp/a.max*100)+'%';$('p2Hp').style.width=Math.max(0,b.hp/b.max*100)+'%';$('p1Name').textContent=me===0?'TÚ':'RIVAL';$('p2Name').textContent=me===1?'TÚ':'RIVAL';$('p1Build').textContent=build(a);$('p2Build').textContent=build(b);let m=$('centerMessage');if(s.phase==='count'){m.textContent=Math.ceil(s.count);m.classList.remove('hidden')}else if(s.phase==='wait'){m.innerHTML='ESPERANDO RIVAL<small>pásale el enlace</small>';m.classList.remove('hidden')}else if(s.phase==='round'){m.textContent='RONDA TERMINADA';m.classList.remove('hidden')}else m.classList.add('hidden');draft(s);endUI(s)}
function build(p){let x=Object.entries(p.p);return x.length?x.slice(-3).map(([k,v])=>POW[k][0]+(v>1?' ×'+v:'')).join(' · '):'sin poderes'}
function draft(s){let o=$('upgradeOverlay');if(s.phase!=='pick'){o.classList.add('hidden');o.dataset.sig='';pickLock=false;return}o.classList.remove('hidden');let opts=s.opts[me],chosen=s.picked[me],sig=opts.join('|')+'|'+chosen;if(o.dataset.sig===sig)return;o.dataset.sig=sig;$('upgradeCards').innerHTML='';opts.forEach((id,n)=>{let d=POW[id],bt=document.createElement('button');bt.className='power-card rarity-'+d[2];bt.disabled=chosen!=null;bt.innerHTML='<span class="rarity">'+R[d[2]]+'</span><h3>'+d[0]+'</h3><p>'+d[1]+'</p><span class="lvl">NIVEL '+((s.p[me].p[id]||0)+1)+'</span>';bt.onclick=()=>{if(pickLock)return;pickLock=1;if(host)choose(0,n);else conn?.send({type:'pick',n})};$('upgradeCards').appendChild(bt)});$('pickStatus').textContent=chosen==null?'Elige uno. No hay vuelta atrás.':'Elegido. Esperando al rival…'}
function endUI(s){let o=$('matchOverlay');if(s.phase!=='end'){o.classList.add('hidden');return}o.classList.remove('hidden');let win=s.winner===me;$('matchTitle').textContent=win?'VICTORIA':'DERROTA';$('matchSubtitle').textContent=win?'Tu build era un delito.':'Te han cocinado. Pide revancha.';$('rematchBtn').textContent=host?'REVANCHA':'PEDIR REVANCHA'}
function draw(s,n){c.clearRect(0,0,W,H);let g0=c.createLinearGradient(0,0,W,H);g0.addColorStop(0,'#0b1020');g0.addColorStop(1,'#080a10');c.fillStyle=g0;c.fillRect(0,0,W,H);c.strokeStyle='#151b2a';for(let x=0;x<W;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(let y=0;y<H;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}c.strokeStyle='#303a52';c.lineWidth=2;c.strokeRect(35,35,890,470);for(const o of OBS){c.fillStyle='#121827';c.fillRect(o.x,o.y,o.w,o.h);c.strokeRect(o.x,o.y,o.w,o.h)}if(!s)return;s.b.forEach(q=>{c.shadowColor=COL[q.o];c.shadowBlur=12;c.fillStyle=COL[q.o];c.beginPath();c.arc(q.x,q.y,q.r,0,7);c.fill();c.shadowBlur=0});s.p.forEach((p,i)=>{c.save();if(p.inv&&Math.floor(n/70)%2===0)c.globalAlpha=.4;c.shadowColor=COL[i];c.shadowBlur=20;c.fillStyle=COL[i];c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill();c.shadowBlur=0;c.fillStyle='#090c14';c.beginPath();c.arc(p.x,p.y,10,0,7);c.fill();c.strokeStyle=COL[i];c.lineWidth=4;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x+Math.cos(p.a)*29,p.y+Math.sin(p.a)*29);c.stroke();if(p.shield){c.strokeStyle='#fff';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,25,0,7);c.stroke()}c.restore()})}
function frame(n){let dt=Math.min(.05,(n-last)/1000);last=n;if(!host&&conn?.open){acc+=dt;if(acc>.033){acc=0;conn.send({type:'i',k:mine})}}let s=host?g:view;if(shake){c.save();c.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.8;draw(s,n);c.restore()}else draw(s,n);sync(s);requestAnimationFrame(frame)}
function pos(e){let r=cv.getBoundingClientRect();mine.ax=(e.clientX-r.left)*W/r.width;mine.ay=(e.clientY-r.top)*H/r.height}
addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(['KeyW','KeyA','KeyS','KeyD','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyW')mine.u=1;if(e.code==='KeyS')mine.d=1;if(e.code==='KeyA')mine.l=1;if(e.code==='KeyD')mine.r=1;if(e.code==='Space')mine.dash=1},{passive:false});
addEventListener('keyup',e=>{if(e.code==='KeyW')mine.u=0;if(e.code==='KeyS')mine.d=0;if(e.code==='KeyA')mine.l=0;if(e.code==='KeyD')mine.r=0;if(e.code==='Space')mine.dash=0});cv.onpointermove=pos;cv.onpointerdown=e=>{if(e.button===0)mine.fire=1};addEventListener('pointerup',()=>mine.fire=0);addEventListener('blur',()=>mine.u=mine.d=mine.l=mine.r=mine.fire=mine.dash=0);
$('hostBtn').onclick=hostGame;$('joinForm').onsubmit=e=>{e.preventDefault();joinGame($('roomInput').value)};$('roomInput').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);$('leaveBtn').onclick=()=>{let u=new URL(location.href);u.searchParams.delete('room');history.replaceState({},'',u);clean()};$('copyBtn').onclick=async()=>{let u=new URL(location.href);u.searchParams.set('room',code);try{await navigator.clipboard.writeText(u.toString());$('copyBtn').textContent='COPIADO'}catch{prompt('Copia el enlace:',u.toString())}};$('rematchBtn').onclick=()=>host&&g?.phase==='end'?(g=fresh(),startRound(),send(1)):conn?.send({type:'rematch'});
let q=new URL(location.href).searchParams.get('room');if(q)$('roomInput').value=q.toUpperCase().slice(0,6);if(typeof Peer==='undefined')status('No se pudo cargar la conexión online. Recarga.',1);requestAnimationFrame(frame);
})();
